### ISSUE TITLE
ModuleNotFoundError: No module named 'bluepy'

### ISSUE THREAD

**Issue by di3t0** [michaelmiklis/loxberry-plugin-miflora#2]
Habe jetetz die Version 2.0.3 des Loxberry, es kommen keine daten rein von den Sensoren.

root@loxberry:~# /usr/bin/python3 /opt/loxberry/bin/plugins/xiaomi-miflora/miflora.py
14.12.2019 15:14:33  INFO Scanning for Xiaomi MiFlora devices (takes up to 10 seconds)
Traceback (most recent call last):
  File "/opt/loxberry/bin/plugins/xiaomi-miflora/miflora.py", line 305, in <module>
    main()
  File "/opt/loxberry/bin/plugins/xiaomi-miflora/miflora.py", line 76, in main
    devices = miflora_scanner.scan(BluepyBackend, scanTimeout)
  File "/opt/loxberry/bin/plugins/xiaomi-miflora/miflora/miflora_scanner.py", line 16, in scan
    for (mac, name) in backend.scan_for_devices(timeout):
  File "/usr/local/lib/python3.7/dist-packages/btlewrap/bluepy.py", line 111, in scan_for_devices
    from bluepy.btle import Scanner
ModuleNotFoundError: No module named 'bluepy'

**Comment by michaelmiklis** [comment]
Bitte mal die neue Version 2.0.1 des Plugins probieren
